#!/bin/sh

uci set luci.main.lang=auto
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

rm -f /www/luci-static/resources/view/status/include/50_dsl.js
rm -f /www/luci-static/resources/view/status/include/70_ddns.js
rm -f /www/luci-static/resources/view/status/include/80_minidlna.js
rm -f /www/luci-static/resources/view/status/include/80_upnp.js

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's#admin/services#admin/nas#g' /usr/lib/lua/luci/view/aria2/settings_header.htm
sed -i 's/services/nas/g' /root/usr/share/luci/menu.d/luci-app-hd-idle.json
sed -i 's/services/nas/g' /root/usr/share/luci/menu.d/luci-app-minidlna.json
sed -i 's/services/nas/g' /root/usr/share/luci/menu.d/luci-app-mjpg-streamer.json
sed -i 's/services/nas/g' /root/usr/share/luci/menu.d/luci-app-p910nd.json
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua

ln -sf /sbin/ip /usr/bin/ip

sed -i 's#https://downloads.openwrt.org#https://mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf






sed -i 's/root::0:0:99999:7:::/root:$1$Je43Lli2$4qj4Nw1xWPrs9WEtY8ArC1:0:0:99999:7:::/g' /etc/shadow







mkdir -p /home/folder

chmod 777 /home/folder

rm -rf /etc/samba/smb.conf

mkdir -p /etc/samba/ && chmod 777 /etc/samba/

echo "[global]
        netbios name = Router
        display charset = UTF-8
        interfaces = lo br-lan
        server string = Router
        unix charset = UTF-8
        workgroup = WORKGROUP
        bind interfaces only = yes
        deadtime = 30
        enable core files = no
        invalid users = root
        local master = yes
        map to guest = Bad User
        max protocol = SMB2
        min receivefile size = 16384
        null passwords = yes
        passdb backend = smbpasswd
        security = user
        smb passwd file = /etc/samba/smbpasswd
        socket options = TCP_NODELAY IPTOS_LOWDELAY
        use sendfile = yes
[homes]
        comment     = Home Directories
        browsable   = no
        read only   = no
        create mode = 0750
[Network Shares]
        path = /home/folder
        read only = no
        guest ok = yes
        create mask = 0666
        directory mask = 0777
        browseable = yes
	
	" > /etc/samba/smb.conf
        
        
        



rm -rf /etc/pdnsd.conf

echo "// Sample pdnsd configuration file. Must be customized to obtain a working pdnsd setup!
// Read the pdnsd.conf(5) manpage for an explanation of the options.
// Add or remove '#' in front of options you want to disable or enable, respectively.
// Remove '/*' and '*/' to enable complete sections.
global {
        perm_cache=off;
        cache_dir="/var/pdnsd";
#       pid_file = /var/run/pdnsd.pid;
        run_as="nobody";
        server_ip = 127.0.0.1;  # Use eth0 here if you want to allow other
                                # machines on your network to query pdnsd.
        status_ctl = on;
#       paranoid=on;       # This option reduces the chance of cache poisoning
                           # but may make pdnsd less efficient, unfortunately.
        query_method=tcp_udp;
        min_ttl=1;         # Retain cached entries at least 1 second.
        max_ttl=1w;        # One week.
        timeout=10;        # Global timeout option (10 seconds).
        neg_domain_pol=on;
        udpbufsize=1024;   # Upper limit on the size of UDP messages.
}
# The following section is most appropriate if you have a fixed connection to
# the Internet and an ISP which provides good DNS servers.
server {
        label= "myisp";
        ip = 208.67.222.222;  # Put your ISP's DNS-server address(es) here.
        port = 443;
#       proxy_only=on;     # Do not query any name servers beside your ISP's.
                           # This may be necessary if you are behind some
                           # kind of firewall and cannot receive replies
                           # from outside name servers.
        timeout=4;         # Server timeout; this may be much shorter
                           # that the global timeout option.
        uptest=none;         # Test if the network interface is active.
        interface=eth0;    # The name of the interface to check.
        interval=10m;      # Check every 10 minutes.
        caching=off;
	purge_cache=on;   # Keep stale cache entries in case the ISP's
                           # DNS servers go offline.
        edns_query=yes;    # Use EDNS for outgoing queries to allow UDP messages
                           # larger than 512 bytes. May cause trouble with some
                           # legacy systems.
#       exclude=.thepiratebay.org,  # If your ISP censors certain names, you may
#               .thepiratebay.se,   # want to exclude them here, and provide an
#               .piratebay.org,     # alternative server section below that will
#               .piratebay.se;      # successfully resolve the names.
}
/*
# The following section is more appropriate for dial-up connections.
# Read about how to use pdnsd-ctl for dynamic configuration in the documentation.
server {
        label= "dialup";
#       file = "/etc/ppp/resolv.conf";  # Preferably do not use /etc/resolv.conf
        ip = 208.67.222.222;
        port = 443;
        proxy_only=on;
        timeout=6;
        uptest=none;
        interface = ppp0;
        interval=10m;       # Check the interface every 10 seconds.
        caching=off;
	purge_cache=on;
        preset=off;
}
*/
/*
# The servers provided by OpenDNS are fast, but they do not reply with
# NXDOMAIN for non-existant domains, instead they supply you with an
# address of one of their search engines. They also lie about the addresses of
# of the search engines of google, microsoft and yahoo.
# If you do not like this behaviour the "reject" option may be useful.
server {
        label = "opendns";
        ip = 208.67.222.222;
        port = 443;
        reject = 208.69.32.0/24,  # You may need to add additional address ranges
                 208.69.34.0/24,  # here if the addresses of their search engines
                 208.67.219.0/24; # change.
        reject_policy = fail;     # If you do not provide any alternative server
                                  # sections, like the following root-server
                                  # example, "negate" may be more appropriate here.
        timeout = 6;
        uptest = none;            # Test availability using ICMP echo requests.
#        ping_timeout = 100;       # ping test will time out after 10 seconds.
        interval = 15m;           # Test every 15 minutes.
        caching=off;
	preset = off;
}
*/
/*
# This section is meant for resolving from root servers.
server {
        label = "root-servers";
#        root_server = discover; # Query the name servers listed below
                                # to obtain a full list of root servers.
#        randomize_servers = on; # Give every root server an equal chance
                                # of being queried.
        ip = 208.67.220.220;     # This list will be expanded to the full
        port = 443;
        timeout = 6;
#        uptest = query;         # Test availability using empty DNS queries.
	uptest = none;
#       query_test_name = .;    # To be used if remote servers ignore empty queries.
        interval = 10m;         # Test every half hour.
	caching=off;
#        ping_timeout = 300;     # Test should time out after 30 seconds.
        purge_cache = on;
#       edns_query = yes;       # Use EDNS for outgoing queries to allow UDP messages
                                # larger than 512 bytes. May cause trouble with some
                                # legacy systems.
        exclude = .localdomain;
        policy = included;
        preset = off;
}
*/
source {
        owner=localhost;
#       serve_aliases=on;
        file="/etc/hosts";
}
/*
include {file="/etc/pdnsd.include";}    # Read additional definitions from /etc/pdnsd.include.
*/
rr {
        name=localhost;
        reverse=on;
        a=127.0.0.1;
        owner=localhost;
        soa=localhost,root.localhost,42,86400,900,86400,86400;
}
/*
neg {
        name=doubleclick.net;
        types=domain;   # This will also block xxx.doubleclick.net, etc.
}
*/
/*
neg {
        name=bad.server.com;   # Badly behaved server you don't want to connect to.
        types=A,AAAA;
}
*/" >/etc/pdnsd.conf




######## myaliddns ###########

chmod 777 /usr/sbin

echo "#!/bin/bash
step=2
for (( i = 0; i < 55; i=(i+step) )); do
    /usr/sbin/aliddns
    sleep $step
done
exit 0
" > /usr/sbin/myaliddns

chmod +x /usr/sbin/myaliddns


########### end ##############





echo "#!/bin/bash
echo \"config core 'main'
        option resourcebase '/luci-static/resources'
        option mediaurlbase '/luci-static/infinityfreedom'
        option lang 'en'
config extern 'flash_keep'
        option uci '/etc/config/'
        option dropbear '/etc/dropbear/'
        option openvpn '/etc/openvpn/'
        option passwd '/etc/passwd'
        option opkg '/etc/opkg.conf'
        option firewall '/etc/firewall.user'
        option uploads '/lib/uci/upload/'
config internal 'languages'
        option en 'English'
config internal 'sauth'
        option sessionpath '/tmp/luci-sessions'
        option sessiontime '3600'
config internal 'ccache'
        option enable '1'
config internal 'themes'
        option infinityfreedom '/luci-static/infinityfreedom'
config internal 'diag'
        option dns 'openwrt.org'
        option ping 'openwrt.org'
        option route 'openwrt.org'\" >/etc/config/luci" >/usr/sbin/myluci
        
chmod +x /usr/sbin/myluci

echo "30 4 * * 0 sh /usr/sbin/myluci"  >>/etc/crontabs/root





## 添加DNSmasq

chmod +x /etc

mkdir -p /etc/dnsmasq.d && chmod 777 /etc/dnsmasq.d

echo "server=/cn/223.6.6.6
#server=/google.com/208.67.222.222#443
#server=/jp/208.67.222.222#443
#server=/kr/208.67.222.222#443
#server=/hk/208.67.222.222#443
#server=/tw/208.67.222.222#443
#server=/sg/208.67.222.222#443
#server=/my/208.67.222.222#443
#server=/us/208.67.222.222#443
#server=/uk/208.67.222.222#443
#server=/de/208.67.222.222#443
#server=/fr/208.67.222.222#443
#server=/it/208.67.222.222#443
# china top sites
server=/baidu.com/223.6.6.6
server=/qq.com/223.6.6.6
server=/taobao.com/223.6.6.6
server=/so.com/223.6.6.6
server=/tmall.com/223.6.6.6
server=/360.cn/223.6.6.6
server=/360.com/223.6.6.6
server=/sina.com.cn/223.6.6.6
server=/alicdn.com/223.6.6.6
server=/sogou.com/223.6.6.6
server=/163.com/223.6.6.6
server=/sohu.com/223.6.6.6
server=/iqiyi.com/223.6.6.6
server=/bilibili.com/223.6.6.6
server=/jd.com/223.6.6.6
server=/eastday.com/223.6.6.6
server=/weibo.com/223.6.6.6
server=/tencent.com/223.6.6.6
server=/2345.com/223.6.6.6
server=/youku.com/223.6.6.6
server=/hao123.com/223.6.6.6
server=/mgtv.com/223.6.6.6
server=/eastmoney.com/223.6.6.6
server=/autohome.com.cn/223.6.6.6
server=/suning.com/223.6.6.6
server=/douban.com/223.6.6.6
server=/360kan.com/223.6.6.6
server=/360doc.com/223.6.6.6
server=/cctv.com/223.6.6.6
server=/douyu.com/223.6.6.6
server=/pcauto.com.cn/223.6.6.6
server=/fun.tv/223.6.6.6
server=/smzdm.com/223.6.6.6
server=/4399.com/223.6.6.6
server=/pptv.com/223.6.6.6
server=/bitauto.com/223.6.6.6
server=/xcar.com.cn/223.6.6.6
server=/huya.com/223.6.6.6
server=/news18a.com/223.6.6.6
server=/china.com/223.6.6.6
server=/docin.com/223.6.6.6
server=/zhihu.com/223.6.6.6
server=/126.com/223.6.6.6
server=/toutiao.com/223.6.6.6
server=/alimama.com/223.6.6.6
server=/duba.com/223.6.6.6
server=/qihoo.com/223.6.6.6
server=/alipay.com/223.6.6.6
server=/huanqiu.com/223.6.6.6
server=/1688.com/223.6.6.6
server=/zol.com.cn/223.6.6.6
server=/10086.cn/223.6.6.6
server=/mama.cn/223.6.6.6
server=/tianya.cn/223.6.6.6
server=/people.com.cn/223.6.6.6
server=/58.com/223.6.6.6
server=/cheshi.com/223.6.6.6
server=/doc88.com/223.6.6.6
server=/ctrip.com/223.6.6.6
server=/taofen8.com/223.6.6.6
server=/pconline.com.cn/223.6.6.6
server=/etao.com/223.6.6.6
server=/chinatax.gov.cn/223.6.6.6
server=/ccb.com.cn/223.6.6.6
server=/youth.cn /223.6.6.6
server=/dianping.com/223.6.6.6
server=/icbc.com.cn/223.6.6.6
server=/csdn.net/223.6.6.6
server=/189.cn/223.6.6.6
server=/dingtalk.com/223.6.6.6
server=/zhaopin.com/223.6.6.6
server=/cnblogs.com/223.6.6.6
server=/chinaz.com/223.6.6.6
server=/ali213.net/223.6.6.6
server=/fang.com/223.6.6.6
server=/2144.com/223.6.6.6
server=/cnki.net/223.6.6.6
server=/3dmgame.com/223.6.6.6
server=/anjuke.com/223.6.6.6
server=/tudou.com/223.6.6.6
server=/58che.com/223.6.6.6
server=/mi.com/223.6.6.6
server=/12306.cn/223.6.6.6
server=/51job.com/223.6.6.6
server=/52pojie.cn/223.6.6.6
server=/51credit.com/223.6.6.6
server=/hupu.com/223.6.6.6
server=/liqu.com/223.6.6.6
server=/120ask.com/223.6.6.6
server=/ourgame.com/223.6.6.6
server=/miui.com/223.6.6.6
server=/10010.com/223.6.6.6
server=/cntv.cn/223.6.6.6
server=/qidian.com/223.6.6.6
server=/youdao.com/223.6.6.6
server=/66law.cn/223.6.6.6
server=/hexun.com/223.6.6.6
server=/aliyun.com/223.6.6.6
server=/alibabacloud.com/223.6.6.6
server=/wps.cn/223.6.6.6
server=/jdpay.com/223.6.6.6
server=/51bi.com/223.6.6.6
server=/cmbchina.com/223.6.6.6
server=/abchina.com/223.6.6.6
server=/ksyun.com/223.6.6.6
server=/huawei.com/223.6.6.6
server=/huaweicloud.com/223.6.6.6
server=/51cto.com/223.6.6.6
server=/51bi.com/114.114.114.114
server=/xiami.com/114.114.114.114
server=/vip.com/114.114.114.114
server=/manmanbuy.com/114.114.114.114
server=/39.net/114.114.114.114
server=/jb51.net/114.114.114.114
server=/bendibao.com/114.114.114.114
server=/xinhuanet.com/114.114.114.114
server=/cnki.com.cn/114.114.114.114
server=/le.com/114.114.114.114
server=/gamersky.com/114.114.114.114
server=/chsi.com.cn/114.114.114.114
server=/jrj.com.cn/114.114.114.114
server=/fliggy.com/114.114.114.114
server=/zybang.com/114.114.114.114
server=/onlinedown.net/114.114.114.114
server=/yesky.com/114.114.114.114
server=/chinaacc.com/114.114.114.114
server=/ci123.com/114.114.114.114
server=/10jqka.com.cn/114.114.114.114
server=/miercn.com/114.114.114.114
server=/mydrivers.com/114.114.114.114
server=/geihui.com/114.114.114.114
server=/chinanews.com/114.114.114.114
server=/kugou.com/114.114.114.114
server=/ithome.com/114.114.114.114
server=/xiaohongshu.com/114.114.114.114
server=/jjwxc.net/114.114.114.114
server=/vmall.com/114.114.114.114
server=/zhanqi.tv/114.114.114.114
server=/sina.cn/114.114.114.114
server=/haodf.com/114.114.114.114
server=/51test.net/114.114.114.114
server=/acfun.cn/114.114.114.114
server=/fanli.com/114.114.114.114
server=/qunar.com/114.114.114.114
server=/nipic.com/114.114.114.114
server=/offcn.com/114.114.114.114
server=/qichacha.com/114.114.114.114
server=/it168.com/114.114.114.114
server=/mafengwo.cn/114.114.114.114
server=/mafengwo.net/223.6.6.6
server=/dangdang.com/114.114.114.114
server=/xunlei.com/114.114.114.114
server=/7k7k.com/114.114.114.114
server=/focus.cn/114.114.114.114
server=/weibo.cn/114.114.114.114
server=/xueqiu.com/114.114.114.114
server=/pc6.com/114.114.114.114
server=/ganji.com/114.114.114.114
server=/liepin.com/114.114.114.114
server=/meituan.com/114.114.114.114
server=/feng.com/114.114.114.114
server=/xuetangx.com/114.114.114.114
server=/weiyun.com/114.114.114.114
# domain register by myself 自己的域名
server=/interstellar.bid/223.6.6.6
server=/interstellar.men/223.6.6.6
server=/jonesky.bid/223.6.6.6
server=/ghoul.bid/223.6.6.6
server=/ghoul.men/223.6.6.6
server=/christopher-nolan.men/223.6.6.6
server=/nikuang.men/223.6.6.6
server=/stitch-chang.men/223.6.6.6
# china cdn
server=/.1test.cn/119.29.29.29#53
server=/.360wzb.cn/119.29.29.29#53
server=/.51cdn.com/119.29.29.29#53
server=/.5test.cn/119.29.29.29#53
server=/.aicdn.com/119.29.29.29#53
server=/.alikunlun.com/119.29.29.29#53
server=/.alikunlun.net/119.29.29.29#53
server=/.b2r.com.cn/119.29.29.29#53
server=/.baiduyundns.cn/119.29.29.29#53
server=/.baiduyundns.com/119.29.29.29#53
server=/.baiduyundns.net/119.29.29.29#53
server=/.bcedns.cn/119.29.29.29#53
server=/.bcedns.com/119.29.29.29#53
server=/.bcedns.net/119.29.29.29#53
server=/.bdydns.cn/119.29.29.29#53
server=/.bdydns.com/119.29.29.29#53
server=/.bdydns.net/119.29.29.29#53
server=/.blueit.com/119.29.29.29#53
server=/.blueit.org.cn/119.29.29.29#53
server=/.cachecn.com/119.29.29.29#53
server=/.cachecn.net/119.29.29.29#53
server=/.cc-1.com/119.29.29.29#53
server=/.cc-cps.cn/119.29.29.29#53
server=/.cc-cps.com.cn/119.29.29.29#53
server=/.cc-cps.com/119.29.29.29#53
server=/.cc-cps.mobi/119.29.29.29#53
server=/.cc-cps.net/119.29.29.29#53
server=/.ccbench.com/119.29.29.29#53
server=/.ccgslb.cn/119.29.29.29#53
server=/.ccgslb.com.cn/119.29.29.29#53
server=/.ccgslb.com/119.29.29.29#53
server=/.ccgslb.net.cn/119.29.29.29#53
server=/.ccgslb.net/119.29.29.29#53
server=/.ccindex.cn/119.29.29.29#53
server=/.ccindex.com.cn/119.29.29.29#53
server=/.ccmplus.cn/119.29.29.29#53
server=/.ccmplus.com.cn/119.29.29.29#53
server=/.ccmplus.net/119.29.29.29#53
server=/.cdn2cdn.net/119.29.29.29#53
server=/.cdnetworks.net/119.29.29.29#53
server=/.cdngc.net/119.29.29.29#53
server=/.cdnsvc.cn/119.29.29.29#53
server=/.cdnsvc.com.cn/119.29.29.29#53
server=/.cdnsvc.com/119.29.29.29#53
server=/.cdnsvc.net.cn/119.29.29.29#53
server=/.cdnsvc.net/119.29.29.29#53
server=/.cdntip.com/119.29.29.29#53
server=/.cdnudns.com/119.29.29.29#53
server=/.chinacache.com.cn/119.29.29.29#53
server=/.chinacache.com/119.29.29.29#53
server=/.chinacache.net/119.29.29.29#53
server=/.chinacache.org/119.29.29.29#53
server=/.chinanetcenter.com/119.29.29.29#53
server=/.cloudcdn.cn/119.29.29.29#53
server=/.cloudcdn.net/119.29.29.29#53
server=/.clouddn.com/119.29.29.29#53
server=/.cloudglb.com/119.29.29.29#53
server=/.cloudglb.net/119.29.29.29#53
server=/.cloudtcp.net/119.29.29.29#53
server=/.cloudxns.com/119.29.29.29#53
server=/.cloudxns.net/119.29.29.29#53
server=/.dnspao.com/119.29.29.29#53
server=/.fastcdn.com /119.29.29.29#53
server=/.fastweb.com.cn/119.29.29.29#53
server=/.fastwebcdn.com/119.29.29.29#53
server=/.ffdns.net/119.29.29.29#53
server=/.fsspace.cn/119.29.29.29#53
server=/.fsspace.com.cn/119.29.29.29#53
server=/.fsspace.com/119.29.29.29#53
server=/.fwcdn.com/119.29.29.29#53
server=/.fwcdn.net/119.29.29.29#53
server=/.fwdns.net/119.29.29.29#53
server=/.fwmob.com/119.29.29.29#53
server=/.gccdn.net/119.29.29.29#53
server=/.gslbsvc.cn/119.29.29.29#53
server=/.gslbsvc.com.cn/119.29.29.29#53
server=/.gslbsvc.com/119.29.29.29#53
server=/.gslbsvc.net.cn/119.29.29.29#53
server=/.gslbsvc.net/119.29.29.29#53
server=/.hacdn.com/119.29.29.29#53
server=/.hacdn.net/119.29.29.29#53
server=/.hadns.net/119.29.29.29#53
server=/.hdslb.com/119.29.29.29#53
server=/.hdslb.net/119.29.29.29#53
server=/.hd-cdn.com/119.29.29.29#53
server=/.igslb.net/119.29.29.29#53
server=/.kunlunaq.com/119.29.29.29#53
server=/.kunlunar.com/119.29.29.29#53
server=/.kunlunca.com/119.29.29.29#53
server=/.kunluncan.com/119.29.29.29#53
server=/.kunlunea.com/119.29.29.29#53
server=/.kunlungem.com/119.29.29.29#53
server=/.kunlungr.com/119.29.29.29#53
server=/.kunlunhuf.com/119.29.29.29#53
server=/.kunlunle.com/119.29.29.29#53
server=/.kunlunli.com/119.29.29.29#53
server=/.kunlunno.com/119.29.29.29#53
server=/.kunlunpi.com/119.29.29.29#53
server=/.kunlunra.com/119.29.29.29#53
server=/.kunlunsa.com/119.29.29.29#53
server=/.kunlunsc.com/119.29.29.29#53
server=/.kunlunsl.com/119.29.29.29#53
server=/.kunlunso.com/119.29.29.29#53
server=/.kunlunta.com/119.29.29.29#53
server=/.kunlunvi.com/119.29.29.29#53
server=/.kunlunwe.com/119.29.29.29#53
server=/.lxdns.com/119.29.29.29#53
server=/.lxdns.net/119.29.29.29#53
server=/.lxsvc.cn /119.29.29.29#53
server=/.lxsvc.cn/119.29.29.29#53
server=/.lxsvc.net/119.29.29.29#53
server=/.myqcloud.com/119.29.29.29#53
server=/.myxns.cn/119.29.29.29#53
server=/.myxns.com.cn/119.29.29.29#53
server=/.myxns.net.cn/119.29.29.29#53
server=/.myxns.org/119.29.29.29#53
server=/.netcenter.com.cn/119.29.29.29#53
server=/.newdefend.cn/119.29.29.29#53
server=/.newdefend.com.cn/119.29.29.29#53
server=/.newdefend.com/119.29.29.29#53
server=/.newdefend.net.cn/119.29.29.29#53
server=/.newdefend.net/119.29.29.29#53
server=/.newdefend.org.cn/119.29.29.29#53
server=/.newdefend.org/119.29.29.29#53
server=/.ourglb0.com/119.29.29.29#53
server=/.ourwebat.com/119.29.29.29#53
server=/.ourwebcdn.com/119.29.29.29#53
server=/.qbox.me/119.29.29.29#53
server=/.qcloud.com/119.29.29.29#53
server=/.qingcdn.com/119.29.29.29#53
server=/.qiniudn.com/119.29.29.29#53
server=/.qiniudns.com/119.29.29.29#53
server=/.speedupchina.com/119.29.29.29#53
server=/.speedupchina.net/119.29.29.29#53
server=/.sz-dns.net/119.29.29.29#53
server=/.tcdn.qq.com/119.29.29.29#53
server=/.tlgslb.com /119.29.29.29#53
server=/.wangsu.com/119.29.29.29#53
server=/.webluker.com/119.29.29.29#53
server=/.wscdns.com/119.29.29.29#53
server=/.wsngb.com/119.29.29.29#53
server=/.xgslb.net/119.29.29.29#53
server=/.yunjiasu-cdn.net/119.29.29.29#53
## 缓存相关设置
cache-size=512
neg-ttl=10
# 返回给客户端的ttl，域名大于10秒，则取10s，这样防止电脑dns缓存过久
# 超过20s的ttl不给client
max-ttl=20
# dnsmasq缓存。如果域名cache 时间超过300s，则dnsmasq缓存5分钟
max-cache-ttl=300
# Whenever /etc/resolv.conf is re-read or the upstream servers are set via DBus, clear the DNS cache. This is useful when new nameservers may have different data than that held in cache.
# --clear-on-reload
## 自己的域名
## Line183 第183行已写
#server=/.interstellar.men/223.6.6.6#53
#存在抢答，SNI重置的域名有 gfw_list 通过 TCP 走代理查询，境内域名查询不丢包就好，gfw_list 漏网之鱼如www.mnd.gov.tw,就通过下面域名查询
all-servers
#server=208.67.222.222#443
#server=208.67.220.220#5353
#server=1.1.1.2#53
#server=1.0.0.2#53
#server=8.8.8.8#53
server=127.0.0.1#5335
# then PDNSD UncensoredDNS
#
#server=1.1.1.2#53
#server=223.6.6.6#53
server=208.67.222.222#443
server=208.67.220.220#5353
" >/etc/dnsmasq.d/accelerated-domains.china.conf






## 修改 LAN 多网口


chmod +x /etc/config

rm -rf /etc/config/network

echo "config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'
config globals 'globals'
        option ula_prefix 'fd06:82ed:679a::/48'
config interface 'lan'
        option type 'bridge'
        option ifname 'eth1 eth2 eth3 eth4 eth5 eth6 eth7 eth8 eth9 eth10 eth11 eth12'
        option proto 'static'
        option ipaddr '192.168.10.1'
        option netmask '255.255.255.0'
        option ip6assign '60'
        list dns '208.67.222.222'
        list dns '208.67.220.220'
config interface 'wan'
        option ifname 'eth0'
        option proto 'dhcp'
list dns '208.67.222.222'
list dns '208.67.220.220'
config interface 'wan6'
        option ifname 'eth0'
        option proto 'dhcpv6'
" >/etc/config/network



# 修改监听端口
sed -i 's|0.0.0.0:80|0.0.0.0:8888|g' /etc/config/uhttpd
# 修改访问地址
sed -i 's|192.168.1.1|192.168.10.1|g' /etc/config/network
# 修改hostname
sed -i '|OpenWrt|Interstellar|' /etc/config/network
# 

#

#

#























[ -f '/bin/bash' ] && sed -i 's|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g' /etc/passwd

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

# NEVER DROP THE EXISTING AUTHORS INFO | 禁止删除现有作者信息
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION=''" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt Snapshot Official | Mod 21.02 By CTCGFW'" >> /etc/openwrt_release

# NEVER DROP THE EXISTING AUTHORS INFO | 禁止删除现有作者信息
sed -i 's/LuCI Master/LuCI Snapshot Official/g' /usr/lib/lua/luci/version.lua
sed -i '/luciversion/d' /usr/lib/lua/luci/version.lua
echo 'luciversion = "Mod 21.02 by CTCGFW"' >> /usr/lib/lua/luci/version.lua

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

mv /etc/openwrt_banner /etc/banner

exit 0
